name: cat_reads
description: Concatenates fastq or fasta files
keywords:
    - fastq
    - fasta
    - concatenate
tools:
    - cat:
        description: |
            The cat utility reads files sequentially, writing them to the standard output.
        documentation: https://www.gnu.org/software/coreutils/manual/html_node/cat-invocation.html
        licence: ['GPL-3.0-or-later']
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: list
        description: |
            List of input FastQ / FASTA files to be concatenated.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: Merged fastq or fasta file
        pattern: "*.{merged.*.gz}"
    - versions:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
    - "@joseespinosa"
    - "@drpatelh"
